Repository devcisive/solumon-frontend, pull requests merged in 2023-10, with the labels that each got.

#23 :white_check_mark: [Feature/component/#15] Axios 설치, 이메일 회원가입 페이지 테스트 API 작성
  solumon-front/package-lock.json
  solumon-front/package.json
  solumon-front/src/main.jsx
  solumon-front/src/mocks/browser.js
  solumon-front/src/mocks/handlers.js
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
Labels: API, 세팅

#25 ✨[Feature/component/#15] 전체 게시판 리스트 페이지 구현
  solumon-front/src/App.jsx
  solumon-front/src/components/PostCard.jsx
  solumon-front/src/mocks/handlers.js
  solumon-front/src/pages/PostList.jsx
Labels: 개발

#27 :sparkles: [Feature/componenet/#15] 홈페이지 소개 페이지 구현
  solumon-front/package-lock.json
  solumon-front/package.json
  solumon-front/src/pages/Start.jsx
Labels: 개발

#28 :sparkles: [Feature/component/#15] 관심주제 선택 페이지 구현
  solumon-front/src/App.jsx
  solumon-front/src/components/InterestTopic.jsx
  solumon-front/src/mocks/handlers.js
  solumon-front/src/pages/ChoiceInterest.jsx
  solumon-front/src/recoil/AllAtom.js
Labels: 개발

#29 :sparkles: [Feature/component/#15]게시물작성페이지 구현
  solumon-front/src/App.jsx
  solumon-front/src/mocks/browser.js
  solumon-front/src/mocks/handlers.js
  solumon-front/src/pages/Posts.jsx
Labels: 개발

#30 :lipstick::white_check_mark::safety_vest: [Feature/component/#15] 로그인 / 회원가입 페이지 로직 추가 & UI 수정
  solumon-front/public/kakao_login.png
  solumon-front/src/pages/Login.jsx
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
  solumon-front/src/pages/sign-up/SignUpKakao.jsx
Labels: 개발, 디자인

#31 :sparkles: [Feature/component/#15] 신고페이지 구현
  solumon-front/src/pages/Ban.jsx
Labels: 개발

#32 :sparkles: [Feature/component/#15] 게시물상세페이지 구현
  solumon-front/src/components/EditMode.jsx
  solumon-front/src/components/HeaderContent.jsx
  solumon-front/src/components/VoteResult.jsx
  solumon-front/src/components/Votes.jsx
  solumon-front/src/pages/PostDetail.jsx
Labels: 개발

#33 📦 [Feature/component/#15] pull 받으면서 사라진 패키지 재설치
  solumon-front/package-lock.json
  solumon-front/package.json
  solumon-front/src/App.jsx
Labels: 세팅

#34 :sparkles: [feature/component/#15] 회원 정보/수정 페이지 구현
  solumon-front/src/pages/UserInfo.jsx
Labels: 개발

#36 :sparkles: [feature/component/#15] 비밀번호 찾기 페이지 구현
  solumon-front/src/pages/FindPassword.jsx
Labels: 개발

#37 :sparkles [feature/component/#15] 카테고리별 상세 게시글을 보여주는 PostCategory 페이지 구현
  solumon-front/src/pages/PostCategory.jsx
Labels: 개발

#38 ✨[feature/component/#15] 로딩 화면 컴포넌트 구현
  solumon-front/src/components/Loading.jsx
Labels: 개발

#40 :bug: [feature/component/#15] 오타 수정
  solumon-front/src/pages/PostDetail.jsx
Labels: 버그 해결

#42 [Feature/component/#15] 브랜치의 파일들 merge
  solumon-front/package-lock.json
  solumon-front/package.json
  solumon-front/public/kakao_login.png
  solumon-front/public/mockServiceWorker.js
  solumon-front/src/App.jsx
  solumon-front/src/components/Button.jsx
  solumon-front/src/components/Chat.jsx
  solumon-front/src/components/EditMode.jsx
  solumon-front/src/components/HeaderContent.jsx
  solumon-front/src/components/InterestTopic.jsx
  solumon-front/src/components/Loading.jsx
  solumon-front/src/components/NavigationBar.jsx
  solumon-front/src/components/Pagination.jsx
  solumon-front/src/components/PostCard.jsx
  solumon-front/src/components/PostInputForm.jsx
  solumon-front/src/components/SearchBar.jsx
  solumon-front/src/components/SortSelector.jsx
  solumon-front/src/components/TabsComponent.jsx
  solumon-front/src/components/TextButton.jsx
  solumon-front/src/components/UserMenu.jsx
  solumon-front/src/components/VoteResult.jsx
  solumon-front/src/components/Votes.jsx
  solumon-front/src/main.jsx
  solumon-front/src/mocks/browser.js
  solumon-front/src/mocks/handlers.js
  solumon-front/src/pages/Ban.jsx
  solumon-front/src/pages/ChoiceInterest.jsx
  solumon-front/src/pages/FindPassword.jsx
  solumon-front/src/pages/Login.jsx
  solumon-front/src/pages/PostCategory.jsx
  solumon-front/src/pages/PostDetail.jsx
  solumon-front/src/pages/PostList.jsx
  solumon-front/src/pages/Posts.jsx
  solumon-front/src/pages/Start.jsx
  solumon-front/src/pages/UserInfo.jsx
  solumon-front/src/pages/WithDraw.jsx
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
  solumon-front/src/pages/sign-up/SignUpKakao.jsx
  solumon-front/src/recoil/AllAtom.js
  solumon-front/vite.config.js
Labels: 배포

#43 :bug: [develop] start 페이지 navigate 링크 수정
  solumon-front/src/pages/Start.jsx
Labels: 버그 해결

#44 :white_check_mark:Test: (chaeeun/develop) 백엔드 연결 테스트
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
Labels: API

#47 💄 [Feature/component/#15] 공통 스타일 수정 & 안내 문구 추가
  solumon-front/src/main.jsx
  solumon-front/src/pages/FindPassword.jsx
  solumon-front/src/pages/Login.jsx
  solumon-front/src/pages/UserInfo.jsx
  solumon-front/src/pages/WithDraw.jsx
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
  solumon-front/src/pages/sign-up/SignUpKakao.jsx
Labels: 디자인

#50 :sparkles::construction: [Feature/component/#15] 이메일 회원가입/로그인 API 연동 후 로직 구현 & 사용자 정보 저장하는 atom 생성
  solumon-front/src/pages/Login.jsx
  solumon-front/src/pages/sign-up/SignUpGeneral.jsx
  solumon-front/src/recoil/AllAtom.js
Labels: API, 개발

#48 [Feature/component/#15] 게시물상세페이지 수정
  solumon-front/public/image/사진1.png
  solumon-front/public/image/사진2.png
  solumon-front/src/components/Button.jsx
  solumon-front/src/components/HeaderContent.jsx
  solumon-front/src/pages/Edit.jsx
  solumon-front/src/pages/PostDetail.jsx
  solumon-front/src/pages/Start.jsx
Labels: 리팩토링

#51 ✨[feature/component/#46] 게시글 목록 실제 API 연동
  solumon-front/src/pages/PostList.jsx
Labels: API, 개발

#56 :art: [Feature/component/#46] 게시물 상세페이지 관련 API연동 및 수정
  solumon-front/src/components/HeaderContent.jsx
  solumon-front/src/components/VoteResult.jsx
  solumon-front/src/components/Votes.jsx
  solumon-front/src/pages/PostDetail.jsx
Labels: API

#57 :art: [Feature/component/#46] 신고페이지 API연동 및 코드수정
  solumon-front/src/pages/Ban.jsx
Labels: API

#60 ✨[Feature/component/#15] 카카오 로그인 기능 구현
  solumon-front/src/pages/ReDirect.jsx
  solumon-front/src/pages/sign-up/SignUpKakao.jsx
Labels: API, 개발

#61 ✨🩹 [Feature/component/#46] 관심주제 페이지 수정
  solumon-front/src/components/InterestTopic.jsx
  solumon-front/src/pages/ChoiceInterest.jsx
Labels: API, 개발
